// Generated by npm run api-types:generate from docs/openapi.json.
// Do not edit by hand.

export type CitySlug = "helsinki" | "espoo" | "vantaa"

export interface HealthResponse {
  status: "ok"
  database: "ok"
  checkedAt: string
}

export interface OpeningHours {
  weekdays: string
  weekends: string
}

export interface ZoneAvailability {
  state: "open" | "closed" | "inactive"
  badge: string
  detail: string
  schedule: string
}

export interface ZoneSummary {
  id: number
  name: string
  city: CitySlug
  type: string
  status: "active" | "inactive"
  hourlyRateEur: number
  latitude: number
  longitude: number
  amenities: string[]
  isOpen: boolean
  availability: ZoneAvailability
  distanceKm?: number
}

export interface ZoneDetail {
  id: number
  name: string
  city: CitySlug
  type: string
  status: "active" | "inactive"
  description: string
  maxCapacity: number
  hourlyRateEur: number
  latitude: number
  longitude: number
  amenities: string[]
  openingHours: OpeningHours
  isOpen: boolean
  availability: ZoneAvailability
  distanceKm?: number
}

export interface ZonesPage {
  items: ZoneSummary[]
  total: number
  page: number
  limit: number
}

export interface ZoneFacetOption {
  value: string
  count: number
}

export interface ZoneFacets {
  city: CitySlug | null
  types: ZoneFacetOption[]
  statuses: ZoneFacetOption[]
  amenities: ZoneFacetOption[]
}

export interface ErrorResponse {
  error: string
  requestId?: string
}
