INSERT INTO zones (
  name,
  city,
  type,
  status,
  description,
  max_capacity,
  hourly_rate_eur,
  latitude,
  longitude,
  amenities,
  opening_hours
) VALUES
(
  'Kamppi Center',
  'helsinki',
  'commercial',
  'active',
  'Multi-level city-center garage connected to Kamppi shopping complex, with live occupancy guidance, EV bays, and direct pedestrian access to the metro and bus terminal.',
  520,
  4.80,
  60.1685,
  24.9318,
  '["EV Charging", "Indoor Parking", "Barrier-Free Access", "License Plate Recognition", "Security Cameras", "Payment Kiosks"]',
  '{"weekdays": "00:00-23:59", "weekends": "00:00-23:59"}'
),
(
  'Esplanadi Park',
  'helsinki',
  'street',
  'active',
  'Premium short-stay curbside parking along Pohjoisesplanadi, used heavily by office visitors, retail traffic, and hotel drop-in parking during daytime hours.',
  86,
  4.20,
  60.1670,
  24.9475,
  '["Street Parking", "Mobile Payment", "Short Stay", "Loading Nearby", "Snow Maintenance Alerts"]',
  '{"weekdays": "08:00-21:00", "weekends": "10:00-18:00"}'
),
(
  'Pasila Tripla Parking',
  'helsinki',
  'commercial',
  'active',
  'Large indoor parking complex serving Mall of Tripla, Pasila station, and adjacent offices, with wide bays, elevator access, and event-day overflow routing.',
  910,
  3.20,
  60.1989,
  24.9330,
  '["EV Charging", "Indoor Parking", "Lift Access", "Security Cameras", "Family Parking", "Payment Kiosks"]',
  '{"weekdays": "05:30-23:30", "weekends": "07:00-23:30"}'
),
(
  'Hakaniemi Market Square',
  'helsinki',
  'street',
  'active',
  'Open-air metered parking near Hakaniemi Market Hall and metro entrances, optimized for market visits, restaurant traffic, and quick city errands.',
  148,
  3.40,
  60.1788,
  24.9506,
  '["Street Parking", "Ticket Machine", "Near Metro", "Mobile Payment", "Quick Turnover Zone"]',
  '{"weekdays": "07:00-21:00", "weekends": "08:00-18:00"}'
),
(
  'Herttoniemi Center Parking',
  'helsinki',
  'commercial',
  'inactive',
  'Neighborhood shopping-center garage in Herttoniemi with covered long-stay capacity, currently partially closed for ventilation, lighting, and guidance-system renewal.',
  340,
  2.40,
  60.1942,
  25.0285,
  '["Covered Parking", "Shopping Access", "Height Limit 2.2 m", "Season Pass Support"]',
  '{"weekdays": "Closed", "weekends": "Closed"}'
),
(
  'Tapiola AINOA Parking',
  'espoo',
  'commercial',
  'active',
  'Direct-access retail garage beneath the AINOA shopping center in Tapiola, with strong turnover during commuting peaks and dedicated EV and family spaces.',
  690,
  3.60,
  60.1782,
  24.8047,
  '["EV Charging", "Indoor Parking", "Family Parking", "Barrier-Free Access", "Retail Validation"]',
  '{"weekdays": "06:00-23:30", "weekends": "08:00-23:30"}'
),
(
  'Iso Omena Metro Garage',
  'espoo',
  'commercial',
  'active',
  'High-capacity parking hall integrated with Iso Omena and Matinkyla metro station, combining shopping, transit, and park-and-ride demand throughout the day.',
  980,
  2.90,
  60.1618,
  24.7380,
  '["Park and Ride Access", "Metro Connection", "EV Charging", "Indoor Parking", "Digital Guidance"]',
  '{"weekdays": "05:30-00:30", "weekends": "07:00-00:30"}'
),
(
  'Sello Parkki',
  'espoo',
  'commercial',
  'active',
  'Leppavaara shopping-center garage serving Sello, nearby offices, and the rail corridor, with frequent use by evening cinema and restaurant visitors.',
  840,
  3.10,
  60.2189,
  24.8127,
  '["Indoor Parking", "Train Station Nearby", "License Plate Recognition", "Security Cameras", "Motorcycle Bays"]',
  '{"weekdays": "06:00-00:00", "weekends": "08:00-00:00"}'
),
(
  'A Bloc Otaniemi Parking',
  'espoo',
  'commercial',
  'active',
  'Compact mixed-use parking facility beneath A Bloc in Otaniemi, serving Aalto University, the metro, and surrounding office tenants during hybrid workdays.',
  260,
  2.70,
  60.1847,
  24.8266,
  '["Metro Connection", "Indoor Parking", "Student Traffic", "EV Charging", "Short Stay"]',
  '{"weekdays": "06:30-22:30", "weekends": "08:00-20:00"}'
),
(
  'Tikkurila Travel Center P1',
  'vantaa',
  'commercial',
  'active',
  'Travel-center garage next to Tikkurila station, tuned for rail passengers, airport-connection users, and all-day commuter parking with digital bay indicators.',
  430,
  2.80,
  60.2937,
  25.0372,
  '["Train Station Nearby", "Indoor Parking", "Commuter Parking", "License Plate Recognition", "Lift Access"]',
  '{"weekdays": "04:30-01:00", "weekends": "05:30-01:00"}'
),
(
  'Jumbo Retail Park Hall',
  'vantaa',
  'commercial',
  'active',
  'Large-format retail parking hall serving Jumbo and Flamingo, with extended evening demand, family bays, and a mix of short-stay and leisure traffic.',
  1120,
  3.00,
  60.2918,
  24.9635,
  '["Indoor Parking", "Family Parking", "EV Charging", "Cinema Traffic", "Security Cameras", "Wide Bays"]',
  '{"weekdays": "07:00-00:30", "weekends": "08:00-00:30"}'
),
(
  'Aviapolis Station Park and Ride',
  'vantaa',
  'street',
  'active',
  'Surface and deck-style commuter parking close to Aviapolis station, designed for rail transfer users heading toward the airport and central Helsinki.',
  318,
  1.80,
  60.3171,
  24.9689,
  '["Park and Ride Access", "Train Station Nearby", "Mobile Payment", "Open Air", "Long Stay"]',
  '{"weekdays": "04:30-23:59", "weekends": "05:30-23:59"}'
);
